### ISSUE TITLE
eZ Class Spec transformer

### ISSUE THREAD

**Issue by nmeirik** [transfer-framework/commons#9]
The tool eZ Class Spec (https://bitbucket.org/Netmaking/ezclasspec) produces a JSON formatted content type specification file. It would be great if this file format could be converted into something that the eZ Platform Transfer library could then use to import content classes.

An example of the eZ Class Spec format can be found here: https://bitbucket.org/Netmaking/website-bundle/commits/2816bea000a8b4e349cfd85ab926f1db822c184e?at=master#chg-Resources/data/contenttypes.ezclasses

**Comment by valisj** [comment]
There is a work-in-progress pull request by @htollefsen that will introduce similar functionality: 
https://github.com/htollefsen/examples/commit/581ec90fb62800907d86e74bc2ba4b15e8b6d0ef#diff-310f83d650f3525b95572a6a2342d19fR1. The example folder: https://github.com/htollefsen/examples/tree/master/ezpublish/yaml_to_content_type

In the file linked above, you can see the format accepted by the transfer-ezplatform library. You can subscribe to this PR in order to get updates: https://github.com/transfer-framework/examples/pull/2

**Comment by valisj** [comment]
Reopened per @htollefsen's request.

**Comment by htollefsen** [comment]
Because it's a fixed format, and not just a pile of JSON, it makes sense to have a worker for it. IMO.
